In [1]:
import numpy as np 
import pandas as pd

### Concat / merge

In [3]:
students = pd.DataFrame({
    "id": [1, 2, 3, 4, 5],
    "name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "age": [18, 19, 18, 20, 17]
})


scores = pd.DataFrame({
    "id": [1, 2, 2, 4, 6], 
    "math": [90, 75, 88, 60, 95],
    "english": [85, 80, 78, 70, 88]
})


schools = pd.DataFrame({
    "id": [1, 2, 3, 4, 5],
    "city": ["Almaty", "Astana", "Almaty", "Shymkent", "Astana"],
    "school": ["NIS", "NIS", "RFMSH", "NIS", "Lyceum"]
})

In [4]:
students

   id     name  age
0   1    Alice   18
1   2      Bob   19
2   3  Charlie   18
3   4    David   20
4   5      Eva   17

In [6]:
scores

   id  math  english
0   1    90       85
1   2    75       80
2   2    88       78
3   4    60       70
4   6    95       88

In [7]:
schools

   id      city  school
0   1    Almaty     NIS
1   2    Astana     NIS
2   3    Almaty   RFMSH
3   4  Shymkent     NIS
4   5    Astana  Lyceum

In [10]:
pd.concat([students, scores, schools])

   id     name   age  math  english      city  school
0   1    Alice  18.0   NaN      NaN       NaN     NaN
1   2      Bob  19.0   NaN      NaN       NaN     NaN
2   3  Charlie  18.0   NaN      NaN       NaN     NaN
3   4    David  20.0   NaN      NaN       NaN     NaN
4   5      Eva  17.0   NaN      NaN       NaN     NaN
0   1      NaN   NaN  90.0     85.0       NaN     NaN
1   2      NaN   NaN  75.0     80.0       NaN     NaN
2   2      NaN   NaN  88.0     78.0       NaN     NaN
3   4      NaN   NaN  60.0     70.0       NaN     NaN
4   6      NaN   NaN  95.0     88.0       NaN     NaN
0   1      NaN   NaN   NaN      NaN    Almaty     NIS
1   2      NaN   NaN   NaN      NaN    Astana     NIS
2   3      NaN   NaN   NaN      NaN    Almaty   RFMSH
3   4      NaN   NaN   NaN      NaN  Shymkent     NIS
4   5      NaN   NaN   NaN      NaN    Astana  Lyceum

In [12]:
pd.merge(students, scores, on="id", how="inner") # Берёт только те строки, где id есть в ОБЕИХ таблицах.

   id   name  age  math  english
0   1  Alice   18    90       85
1   2    Bob   19    75       80
2   2    Bob   19    88       78
3   4  David   20    60       70

In [13]:
pd.merge(students, scores, on="id", how="left")

   id     name  age  math  english
0   1    Alice   18  90.0     85.0
1   2      Bob   19  75.0     80.0
2   2      Bob   19  88.0     78.0
3   3  Charlie   18   NaN      NaN
4   4    David   20  60.0     70.0
5   5      Eva   17   NaN      NaN

In [14]:
pd.merge(students, scores, on="id", how="right")

   id   name   age  math  english
0   1  Alice  18.0    90       85
1   2    Bob  19.0    75       80
2   2    Bob  19.0    88       78
3   4  David  20.0    60       70
4   6    NaN   NaN    95       88

In [17]:
d1 = pd.merge(students, scores, on='id', how='outer')
d1

TypeError: merge() got multiple values for argument 'how'

In [18]:
pd.merge(d1, schools, on='id', how='outer')>

   id     name   age  math  english      city  school
0   1    Alice  18.0  90.0     85.0    Almaty     NIS
1   2      Bob  19.0  75.0     80.0    Astana     NIS
2   2      Bob  19.0  88.0     78.0    Astana     NIS
3   3  Charlie  18.0   NaN      NaN    Almaty   RFMSH
4   4    David  20.0  60.0     70.0  Shymkent     NIS
5   5      Eva  17.0   NaN      NaN    Astana  Lyceum
6   6      NaN   NaN  95.0     88.0       NaN     NaN

In [23]:
pd.concat([schools, scores], axis=1)

   id      city  school  id  math  english
0   1    Almaty     NIS   1    90       85
1   2    Astana     NIS   2    75       80
2   3    Almaty   RFMSH   2    88       78
3   4  Shymkent     NIS   4    60       70
4   5    Astana  Lyceum   6    95       88

In [25]:
pd.concat([schools, scores], axis=0)

   id      city  school  math  english
0   1    Almaty     NIS   NaN      NaN
1   2    Astana     NIS   NaN      NaN
2   3    Almaty   RFMSH   NaN      NaN
3   4  Shymkent     NIS   NaN      NaN
4   5    Astana  Lyceum   NaN      NaN
0   1       NaN     NaN  90.0     85.0
1   2       NaN     NaN  75.0     80.0
2   2       NaN     NaN  88.0     78.0
3   4       NaN     NaN  60.0     70.0
4   6       NaN     NaN  95.0     88.0

In [26]:
pd.merge(students, scores, on='id', how='inner')

   id   name  age  math  english
0   1  Alice   18    90       85
1   2    Bob   19    75       80
2   2    Bob   19    88       78
3   4  David   20    60       70

In [27]:
pd.merge(students, scores, on='id', how='right')

   id   name   age  math  english
0   1  Alice  18.0    90       85
1   2    Bob  19.0    75       80
2   2    Bob  19.0    88       78
3   4  David  20.0    60       70
4   6    NaN   NaN    95       88

In [31]:
pd.merge(students, scores, on='id', how='outer')

   id     name   age  math  english
0   1    Alice  18.0  90.0     85.0
1   2      Bob  19.0  75.0     80.0
2   2      Bob  19.0  88.0     78.0
3   3  Charlie  18.0   NaN      NaN
4   4    David  20.0  60.0     70.0
5   5      Eva  17.0   NaN      NaN
6   6      NaN   NaN  95.0     88.0

In [38]:
df = pd.concat([students, scores, schools], axis=1)

In [37]:
df1 = pd.merge(students, scores, on=['id', 'id'], how='outer')
df1

   id     name   age  math  english
0   1    Alice  18.0  90.0     85.0
1   2      Bob  19.0  75.0     80.0
2   2      Bob  19.0  88.0     78.0
3   3  Charlie  18.0   NaN      NaN
4   4    David  20.0  60.0     70.0
5   5      Eva  17.0   NaN      NaN
6   6      NaN   NaN  95.0     88.0

In [39]:
df

   id     name  age  id  math  english  id      city  school
0   1    Alice   18   1    90       85   1    Almaty     NIS
1   2      Bob   19   2    75       80   2    Astana     NIS
2   3  Charlie   18   2    88       78   3    Almaty   RFMSH
3   4    David   20   4    60       70   4  Shymkent     NIS
4   5      Eva   17   6    95       88   5    Astana  Lyceum

In [40]:
df.loc[
    (df['age'] <= 19) &
    (df['city'].str.startswith('A'))
]

   id     name  age  id  math  english  id    city  school
0   1    Alice   18   1    90       85   1  Almaty     NIS
1   2      Bob   19   2    75       80   2  Astana     NIS
2   3  Charlie   18   2    88       78   3  Almaty   RFMSH
4   5      Eva   17   6    95       88   5  Astana  Lyceum

In [47]:
df.groupby('age')['math'].mean()

age
17    95.0
18    89.0
19    75.0
20    60.0
Name: math, dtype: float64

In [50]:
df['Age after 20 years'] = df['age'].apply(lambda x: x + 20)

In [51]:
df

,id,name,age,id,math,english,id,city,school,Age after 20 years
0,1,Alice,18,1,90,85,1,Almaty,NIS,38
1,2,Bob,19,2,75,80,2,Astana,NIS,39
2,3,Charlie,18,2,88,78,3,Almaty,RFMSH,38
3,4,David,20,4,60,70,4,Shymkent,NIS,40
4,5,Eva,17,6,95,88,5,Astana,Lyceum,37

In [61]:
df['rank_name'] = df['name'].rank()
df['rank_age'] = df['age'].rank()
df['Overall_rank'] = df['rank_name'] + df['rank_age']
df

,id,name,age,id,math,english,id,city,school,Age after 20 years,rank,rank_name,rank_age,Overall_rank
0,1,Alice,18,1,90,85,1,Almaty,NIS,38,1.0,1.0,2.5,3.5
1,2,Bob,19,2,75,80,2,Astana,NIS,39,2.0,2.0,4.0,6.0
2,3,Charlie,18,2,88,78,3,Almaty,RFMSH,38,3.0,3.0,2.5,5.5
3,4,David,20,4,60,70,4,Shymkent,NIS,40,4.0,4.0,5.0,9.0
4,5,Eva,17,6,95,88,5,Astana,Lyceum,37,5.0,5.0,1.0,6.0

In [64]:
df['new_name'] = df['name'].apply(lambda x: x.upper())
df

,id,name,age,id,math,english,id,city,school,Age after 20 years,rank,rank_name,rank_age,Overall_rank,new_name
0,1,Alice,18,1,90,85,1,Almaty,NIS,38,1.0,1.0,2.5,3.5,ALICE
1,2,Bob,19,2,75,80,2,Astana,NIS,39,2.0,2.0,4.0,6.0,BOB
2,3,Charlie,18,2,88,78,3,Almaty,RFMSH,38,3.0,3.0,2.5,5.5,CHARLIE
3,4,David,20,4,60,70,4,Shymkent,NIS,40,4.0,4.0,5.0,9.0,DAVID
4,5,Eva,17,6,95,88,5,Astana,Lyceum,37,5.0,5.0,1.0,6.0,EVA

In [68]:
df['math_level'] = np.where(
    df['math'] < 70, 'low', 
    np.where(df['math'].between(70, 88), 'middle', 'high')
)
df

,id,name,age,id,math,english,id,city,school,Age after 20 years,rank,rank_name,rank_age,Overall_rank,new_name,math_level
0,1,Alice,18,1,90,85,1,Almaty,NIS,38,1.0,1.0,2.5,3.5,ALICE,high
1,2,Bob,19,2,75,80,2,Astana,NIS,39,2.0,2.0,4.0,6.0,BOB,middle
2,3,Charlie,18,2,88,78,3,Almaty,RFMSH,38,3.0,3.0,2.5,5.5,CHARLIE,middle
3,4,David,20,4,60,70,4,Shymkent,NIS,40,4.0,4.0,5.0,9.0,DAVID,low
4,5,Eva,17,6,95,88,5,Astana,Lyceum,37,5.0,5.0,1.0,6.0,EVA,high

In [86]:
df2 = pd.read_csv('/Users/danialmendigali/jupyter-datascience/Pandas/data set /Titanic-Dataset.csv')

In [77]:
df2.loc[
    ((df2['Name'].str.startswith('C')) |
    (df2['Name'].str.startswith('A'))) &
    (df2['Age'] > 50)
]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
94,95,0,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,NaN,S
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
249,250,0,2,"Carter, Rev. Ernest Courtenay",male,54.0,1,0,244252,26.0000,NaN,S
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
571,572,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S
695,696,0,2,"Chapman, Mr. Charles Henry",male,52.0,0,0,248731,13.5000,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S

In [92]:
g = df2.pivot_table(index='Pclass', values='Age', aggfunc=['mean', 'max', 'min'])
g.reset_index()

  Pclass       mean   max   min
                Age   Age   Age
0      1  38.233441  80.0  0.92
1      2  29.877630  70.0  0.67
2      3  25.140620  74.0  0.42

In [95]:
df2.sort_index().head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [104]:
df2.sort_values(by=['Pclass', 'Age'], ascending=[False, False]).head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
94,95,0,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,NaN,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
222,223,0,3,"Green, Mr. George Henry",male,51.0,0,0,21440,8.0500,NaN,S
406,407,0,3,"Widegren, Mr. Carl/Charles Peter",male,51.0,0,0,347064,7.7500,NaN,S
631,632,0,3,"Lundahl, Mr. Johan Svensson",male,51.0,0,0,347743,7.0542,NaN,S