In [1]:
import pandas as pd 
import numpy as np

### Optimization and vectorization

In [23]:
df = pd.read_csv('/Users/danialmendigali/jupyter-datascience/Pandas/data set /insurance.csv')

In [14]:
df['sex'].value_counts()

sex
male      676
female    662
Name: count, dtype: int64

In [5]:
def risk_level(row):
    if row['smoker'] == 'yes' and row['bmi'] > 30:
        return 'high'
    elif row['smoker'] == 'yes':
        return 'medium'
    else:
        return 'low'

df['risk'] = df.apply(risk_level, axis=1)

In [15]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [16]:
df['risk'] = np.where(
    (df['smoker'] == 'yes') & (df['bmi'] > 30), 'high',
    np.where(df['smoker'] == 'yes', 'medium', 'low')
)

In [17]:
df.tail()

      age     sex    bmi  children smoker     region     charges    risk
1333   50    male  30.97         3     no  northwest  10600.5483     low
1334   18  female  31.92         0     no  northeast   2205.9808     low
1335   18  female  36.85         0     no  southeast   1629.8335     low
1336   21  female  25.80         0     no  southwest   2007.9450     low
1337   61  female  29.07         0    yes  northwest  29141.3603  medium

### apply = convenient when the logic is complex, but slow.

In [18]:
over_50 = []
for age in df['age']:
    if age > 50:
        over_50.append(1)
    else:
        over_50.append(0)

df['over_50'] = over_50

In [22]:
df.loc[
    (df['age'] < 50)
].head()

,age,sex,bmi,children,smoker,region,charges,risk,over_50
0,19,female,27.900,0,yes,southwest,16884.92400,medium,0
1,18,male,33.770,1,no,southeast,1725.55230,low,0
2,28,male,33.000,3,no,southeast,4449.46200,low,0
3,33,male,22.705,0,no,northwest,21984.47061,low,0
4,32,male,28.880,0,no,northwest,3866.85520,low,0

In [24]:
df['over_50'] = (df['age'] > 50).astype(int)

In [27]:
df.head()

   age     sex     bmi  children smoker     region      charges  over_50
0   19  female  27.900         0    yes  southwest  16884.92400        0
1   18    male  33.770         1     no  southeast   1725.55230        0
2   28    male  33.000         3     no  southeast   4449.46200        0
3   33    male  22.705         0     no  northwest  21984.47061        0
4   32    male  28.880         0     no  northwest   3866.85520        0

In [ ]:
for i in range(50, 39, 1):
    print(i)