In [1]:
import pandas as pd 
import numpy as np

In [135]:
df = pd.read_csv('/Users/danialmendigali/jupyter-datascience/Pandas/data set /insurance.csv')

### Block 1

In [65]:
df.shape[0]

1338

In [66]:
df[df.duplicated()]

     age   sex    bmi  children smoker     region    charges
581   19  male  30.59         0     no  northwest  1639.5631

In [77]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [69]:
df.loc[df.sample(frac=0.1).index, 'age'] = np.nan
df.loc[df.sample(frac=0.1).index, 'bmi'] = np.nan

In [67]:
df.drop_duplicates(inplace=True)

In [71]:
df.shape[0]

1337

In [39]:
df.dropna(inplace=True)

In [76]:
df.fillna({
    'age' : df['age'].mean(),
    'bmi' : df['bmi'].max()
}, inplace=True)

In [83]:
df.loc[
    (df['age'] == df['age'].mean())
].head(5)

          age     sex     bmi  children smoker     region      charges
17  39.261845    male  23.845         0     no  northeast   2395.17155
31  39.261845  female  26.315         0     no  northeast   2198.18985
44  39.261845    male  37.050         1     no  northeast   6079.67150
48  39.261845  female  24.530         0     no  southeast  12629.89670
49  39.261845    male  35.200         1    yes  southeast  38709.17600

In [84]:
df.loc[df.sample(frac=0.08).index, 'sex'] = np.nan
df.loc[df.sample(frac=0.08).index, 'smoker'] = np.nan
df.loc[df.sample(frac=0.08).index, 'region'] = np.nan

In [103]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [93]:
df['region'].mode()[0]

'southeast'

In [101]:
df.loc[
    (df['region'] == 'southeast')
].shape[0]

441

In [104]:
df.fillna({
    'sex' : df['sex'].mode()[0],
    'smoker' : 'unknown',
    'region' : df['region'].mode()[0]
}, inplace=True)

In [106]:
df.head(5)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [130]:
df['risk_level'] = df.apply(
    lambda x: 'high' if (x['smoker'] == 'yes' and x['bmi'] > 30) or (x['smoker'] == 'yes' and x['age'] >= 55)
    else('medium' if x['smoker'] == 'yes' and 25 <= x['bmi'] <= 30 else 'low'),
    axis=1
)

In [111]:
df.loc[
    (df['smoker'] == 'yes')
].head(5)

    age     sex    bmi  children smoker     region     charges risk_level
0    19  female  27.90         0    yes  southwest  16884.9240     medium
11   62  female  26.29         0    yes  southeast  27808.7251       high
14   27    male  42.13         0    yes  southeast  39611.7577       high
19   30    male  35.30         0    yes  southwest  36837.4670       high
23   34  female  31.92         1    yes  northeast  37701.8768       high

In [114]:
def family_status(r):
    if r['children'] >= 3:
        return 'large_family'
    elif r['children'] >= 1 and r['children'] <= 2:
        return 'small_family'
    else:
        return 'no_family'
        
df['family_status'] = df.apply(family_status, axis=1)

In [116]:
df[['children', 'family_status']].head(5)

   children family_status
0         0     no_family
1         1  small_family
2         3  large_family
3         0     no_family
4         0     no_family

In [131]:
df['bmi_category'] = np.where(
    df['bmi'] < 18.5, 'underweight',
    np.where(df['bmi'] < 25, 'normal', 'overweight')
)

In [126]:
df.sort_values(by='bmi', ascending=False).head(5)

,age,sex,bmi,children,smoker,region,charges,risk_level,family_status,bmi_category
1317,18,male,53.13,0,no,southeast,1163.4627,low,no_family,overweight
1047,22,male,52.58,1,yes,southeast,44501.3982,high,small_family,overweight
847,23,male,50.38,1,no,southeast,2438.0552,low,small_family,overweight
116,58,male,49.06,0,no,southeast,11381.3254,low,no_family,overweight
286,46,female,48.07,2,no,northeast,9432.9253,low,small_family,overweight

In [127]:
df['high_charges'] = np.where(
    df['charges'] > df['charges'].mean(), 1, 0
)

In [129]:
df['charges'].mean()

np.float64(13270.422265141257)

In [128]:
df.head(5)

,age,sex,bmi,children,smoker,region,charges,risk_level,family_status,bmi_category,high_charges
0,19,female,27.900,0,yes,southwest,16884.92400,medium,no_family,overweight,1
1,18,male,33.770,1,no,southeast,1725.55230,low,small_family,overweight,0
2,28,male,33.000,3,no,southeast,4449.46200,low,large_family,overweight,0
3,33,male,22.705,0,no,northwest,21984.47061,low,no_family,overweight,1
4,32,male,28.880,0,no,northwest,3866.85520,low,no_family,overweight,0

In [133]:
df['bmi'].max()

np.float64(53.13)

In [145]:
df.loc[
    ((df['bmi'] > 40) & (df['smoker'] == 'yes')) |
    ((df['bmi'] > 45) & (df['age'] > 30))
].head(5)

     age   sex     bmi  children smoker     region      charges
14    27  male  42.130         0    yes  southeast  39611.75770
116   58  male  49.060         0     no  southeast  11381.32540
185   36  male  41.895         3    yes  northeast  43753.33705
265   46  male  42.350         3    yes  southeast  46151.12450
281   54  male  40.565         3    yes  northeast  48549.17835

In [147]:
t = df.pivot_table(index='sex', values='charges', aggfunc=['mean', 'max'])

In [149]:
t

                mean          max
             charges      charges
sex
female  12569.578844  63770.42801
male    13956.751178  62592.87309

In [150]:
t.reset_index()

      sex          mean          max
                charges      charges
0  female  12569.578844  63770.42801
1    male  13956.751178  62592.87309

In [152]:
t2 = df.pivot_table(index='age', values='bmi', aggfunc=['mean', 'max', 'min'])
t2.tail(5)

          mean    max     min
           bmi    bmi     bmi
age
60   30.332826  40.92  18.335
61   32.548261  44.00  21.090
62   32.342609  39.93  21.400
63   31.923478  41.47  21.660
64   32.976136  40.48  22.990

In [153]:
df['rank_charges'] = df['charges'].rank()

In [163]:
df.head(5)

   age     sex     bmi  children smoker     region      charges  rank_charges
0   19  female  27.900         0    yes  southwest  16884.92400        1007.0
1   18    male  33.770         1     no  southeast   1725.55230          59.0
2   28    male  33.000         3     no  southeast   4449.46200         308.0
3   33    male  22.705         0     no  northwest  21984.47061        1099.0
4   32    male  28.880         0     no  northwest   3866.85520         256.0

In [161]:
s1 = df.sort_values(by='rank_charges', ascending=True)
s1.head(5)

      age   sex    bmi  children smoker     region    charges  rank_charges
940    18  male  23.21         0     no  southeast  1121.8739           1.0
808    18  male  30.14         0     no  southeast  1131.5066           2.0
1244   18  male  33.33         0     no  southeast  1135.9407           3.0
663    18  male  33.66         0     no  southeast  1136.3994           4.0
22     18  male  34.10         0     no  southeast  1137.0110           5.0

In [165]:
s2 = df.sort_values(by='charges', ascending=True)
s2.head(5)

      age   sex    bmi  children smoker     region    charges  rank_charges
940    18  male  23.21         0     no  southeast  1121.8739           1.0
808    18  male  30.14         0     no  southeast  1131.5066           2.0
1244   18  male  33.33         0     no  southeast  1135.9407           3.0
663    18  male  33.66         0     no  southeast  1136.3994           4.0
22     18  male  34.10         0     no  southeast  1137.0110           5.0

In [168]:
s2.sort_index().head(5)

   age     sex     bmi  children smoker     region      charges  rank_charges
0   19  female  27.900         0    yes  southwest  16884.92400        1007.0
1   18    male  33.770         1     no  southeast   1725.55230          59.0
2   28    male  33.000         3     no  southeast   4449.46200         308.0
3   33    male  22.705         0     no  northwest  21984.47061        1099.0
4   32    male  28.880         0     no  northwest   3866.85520         256.0

### Block 2