In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('/Users/danialmendigali/jupyter-datascience/Pandas/data set /Titanic-Dataset.csv')

### Working with Strings in Pandas (.str)

In [7]:
df['Sex'] = df['Sex'].str.upper()

In [10]:
df.tail(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"montvila, rev. juozas",MALE,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"graham, miss. margaret edith",FEMALE,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"johnston, miss. catherine helen ""carrie""",FEMALE,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"behr, mr. karl howell",MALE,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"dooley, mr. patrick",MALE,32.0,0,0,370376,7.75,NaN,Q

In [11]:
df['Name'] = df['Name'].str.lower()

In [12]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"braund, mr. owen harris",MALE,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",FEMALE,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"heikkinen, miss. laina",FEMALE,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"futrelle, mrs. jacques heath (lily may peel)",FEMALE,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"allen, mr. william henry",MALE,35.0,0,0,373450,8.0500,NaN,S

In [13]:
df['Sex'] = df['Sex'].str.strip()

In [15]:
df['Name'] = df['Name'].str.strip()

In [16]:
df.tail(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"montvila, rev. juozas",MALE,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"graham, miss. margaret edith",FEMALE,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"johnston, miss. catherine helen ""carrie""",FEMALE,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"behr, mr. karl howell",MALE,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"dooley, mr. patrick",MALE,32.0,0,0,370376,7.75,NaN,Q

In [24]:
df['Name'] = df['Name'].str.replace('mr.', 'Mr', regex=False)    # Заменяет одну подстроку на другую

In [27]:
df.tail(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"montvila, rev. juozas",MALE,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"graham, miss. margaret edith",FEMALE,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"johnston, miss. catherine helen ""carrie""",FEMALE,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"behr, Mr karl howell",MALE,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"dooley, Mr patrick",MALE,32.0,0,0,370376,7.75,NaN,Q

In [51]:
df[df['Name'].str.contains('Mrs.', regex=False, case=False)].head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",FEMALE,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"futrelle, mrs. jacques heath (lily may peel)",FEMALE,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"johnson, mrs. oscar w (elisabeth vilhelmina berg)",FEMALE,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"nasser, mrs. nicholas (adele achem)",FEMALE,14.0,1,0,237736,30.0708,NaN,C
15,16,1,2,"hewlett, mrs. (mary d kingcome)",FEMALE,55.0,0,0,248706,16.0000,NaN,S